### PR TITLE
build: add makefile and rebuild

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by lewis6991** [comment]
@euclidianAce are you able to review this?

**Comment by euclidianAce** [comment]
I'm not a huge fan of adding a make dependency. [I've prototyped a build hook here](https://github.com/teal-language/teal-language-server/blob/type-dependency-fetching/scripts/check-for-teal-types.tl) to prompt the user to download the `lfs` and `dkjson` `.d.tl` files. I did cherry pick the `.gitattributes` commit though.

Thanks for pointing out the annoyance of having to manually set up the type dependencies though!

**Comment by lewis6991** [comment]
Dependency on make? You know that's just standard tooling included in basically every unix distro? It's also optional here and just automates some stuff.

**Comment by euclidianAce** [comment]
Okay, dependency is a strong word, but I do want to be cautious of catering to a unix environment since I do have to use a windows machine occasionally, and don't want to limit these kind of niceties to just unix.

**Comment by lewis6991** [comment]
Hmm fair enough.

I'm not sure adding a 200loc script that depends on private API's in cyan (which is basically alpha at this point) is a better approach. There must be some other cross platform solution. I'm surprised make isn't available in some form on windows.

**Comment by lewis6991** [comment]
Will this not suffice? https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows

**Pull request closed without merging**
